org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

mod_version=2.2.2
mod_id=createsifter
mod_author=oierbravo
mod_name=Create: Sifter

mechanicals = 1.1.1
mechanicals_range = [1.1.0,1.2.0)
# Base Dependencies
minecraft_version = 1.21.1
minecraft_version_range=[1.21.1]

neo_version = 21.1.219
neo_version_range=[21.1.219,)

parchment_minecraft_version = 1.21.1
parchment_version = 2024.11.17

# dependency versions
create_version_range = [6.0.10,6.1.0)
create_version = 6.0.10-280
ponder_version = 1.0.82
flywheel_version = 1.0.6
registrate_version = MC1.21-1.3.0+67
jei_minecraft_version = 1.21.1
jei_version = 19.25.0.322
curios_minecraft_version = 1.21.1
curios_version = 9.2.2

jade_id = 6198776

recipe_viewer = jei

emi_version = 1.1.22+1.21.1

cc_tweaked_enable = false
cc_tweaked_minecraft_version = 1.21.1
cc_tweaked_version = 1.114.2

kubejs_enabled=true
kubejs_version=2101.7.2-build.348
mixin_extras_version = 0.4.1

curseforge_id = 661938
modrinth_id = r018adCw
